### PR TITLE
THNN conversion of volumetric_full_fix

### PR DESCRIPTION
**Pull request by andreaskoepf**
I converted the module. But I noticed that the tests fail some times - this is also the case with your original version.

I always get at least one error when I run `nn.test()`: 

```
VolumetricFullConvolution_simple_test
 Function call failed 
bad argument #2 to '?' (out of range at /home/koepf/torch/pkg/torch/generic/Tensor.c:888)
stack traceback:
    [C]: at 0x7f07c0fde4d0
    [C]: in function '__index'
    /home/koepf/torch/install/share/lua/5.1/nn/test.lua:3252: in function </home/koepf/torch/install/share/lua/5.1/nn/test.lua:3213>
    [C]: in function 'xpcall'
```

But if I execute nn.test() multiple times most of the VolumetricFullConvolution tests fail.

Could you please test with your current state repo version first? You should see a couple of failing tests when running nn.test() for 10 times or so... I think we need to fix these problems first.

### CODE REVIEW

**Comment by andreaskoepf** [comment]
Really strange: I can run `th -l nn -e "nn.test('VolumetricFullConvolution')"` 10x without ever getting an error. If I comment out `VolumetricFullConvolution_simple_test` in test.lua all tests pass all the time. It seems as if the call that fails in the simple_test corrupts some internal state.

**Comment by andreaskoepf** [comment]
OK, there zeroGradParameters() was missing in `VolumetricFullConvolution_simple_test()` and the gradWeight indexing had to be changed since you swapped the input and outputplane dimensions to match SpatialFullConvolution. It would be great if you could run the tests a couple of times on your machine.
In order to prerpare a PR for torch/nn we need a cuda version too. If I understood you right you also did the change for cunn. Could you fork & push to cunn as well?

**Comment by andreaskoepf** [comment]
@fbesse plz let me know how you would like to proceed: Do you want to create a PR for this at torch/nn or should I take care of it?

**Comment by fbesse** [comment]
@andreaskoepf The tests run fine on my machine.
I have a cunn fix but it's also with the old non-THNN way - should we run through the same process or would you like me to do the conversion to THNN as well?

**Comment by fbesse** [comment]
Actually it seems straightforward to convert my changes to THCUNN, so I'll do this.

**Comment by andreaskoepf** [comment]
@fbesse Would be great if you gave it a try. Generally the function calls via FFI to the THNN/THCUNN are straight forward. The only thing you need to take care of is that the THCUNN function signatures  match the THNN ones. For exapmle if an impl uses special buffers for the cuda version those parameters must be on the THNN function signature as well even though they are not used for the CPU impl. But since finput & fgradInput are already passed to the three `VolumetricFullConvolution_*` functions I think this will not be a problem in this case.

**Comment by fbesse** [comment]
@andreaskoepf I've converted it and pushed it to a branch on my repo, see https://github.com/fbesse/cunn/tree/volumetric_full_fix

I've updated the test in the same fashion as the update in nn. Could you please double check that they pass on your build too?

**Comment by andreaskoepf** [comment]
@fbesse nn.testcuda() runs fine. But I made a very strange observation: For the THNN conversion I have nn2 and cunn2 branches that allow cross-checking with the old implementation (e.g. after building nn2 and cunn2 you can use require 'cunn2' to load the old impl side by side with the new one). I ran my original [xtest.lua](https://github.com/andreaskoepf/cunn/blob/cunn2/xtest.lua#L308) check and expected it to fail (since the weight tensor layout changed) - but for some strange reason the VolumetricConv test passed. That means if the weight tensor of the new impl is assigned to an old module the output of the [old module](https://github.com/andreaskoepf/cunn/blob/cunn2/VolumetricFullConvolution.cu) is identical to the [new impl](https://github.com/fbesse/cunn/blob/volumetric_full_fix/lib/THCUNN/VolumetricFullConvolution.cu)... 

Indeed if you compare the THCudaBlas_gemm() calls in both implementations the argument-values seem to effectively become identical. This is even more interesting since the old implementation did not use the weight-tensor size, e.g. it does the gemm call with a 'wrong' nOutputPlane number - nevertheless this produces the output of the new impl.

Do you think tihs is correct? Can you explain it?

**Comment by fbesse** [comment]
Indeed it seems that the gemm call is the same - the old implementation was just seing the weights as an unfolded 1D tensor. This must not be true the other way around, that is, assigning the old weights to the new module since the new module looks at the size of the weight tensor to assign input/output planes.
In the new implementation when deserializing from an old module I added a transpose operation on the weight, but I am now wondering if it should instead be a view with the new shape (I will run more tests on that - I thought transpose was giving me the correct result though).
Could you try doing the following with your code to see if it also passes?
`new_module.weight = old_module.weight:transpose(1, 2):contiguous()`

**Comment by andreaskoepf** [comment]
> new_module.weight = old_module.weight:transpose(1, 2):contiguous()

That is what I originally expected I had to do in order to 'fix' the test. If I add this to the cunn2/xtest.lua file the test fails: LT(<) violation   val=2455.7111816406, condition=1e-12.

Interestingly exactly this line fixes the test of the non-cude nn2/xtest.lua. I will tomorrow once again compare the nn/cunn impls. Just an idea: could it be the old cunn/nn impls did different things?

**Comment by andreaskoepf** [comment]
I created this little test: https://gist.github.com/andreaskoepf/5ba9864c561766f9260e to compare CPU and GPU versions of the current VolumetricFullConvolution .. and it indeed seems as if the GPU does something different the CPU version. Good news is: with your fix impl the output of the test looks like:

```
SpatialFullConvolution: 6.6509901483908e-06 
VolumetricFullConvolution: 9.1297354070978e-05  
```

So, I think your fix is ready for a PR! :shipit:

**Comment by fbesse** [comment]
@andreaskoepf That's great thanks for the test! I will make the two PRs now.

**Pull request merged**
